### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by ebenbaruch** [v-vietlq4/thesis#1]
Hi, 
We have noticed you cloned our repo (PETA): https://github.com/Alibaba-MIIL/PETA
Can you please modify the link in the ReadMe file of the pretrained-model that you used today?

Please modify to this one:
https://miil-public-eu.oss-eu-central-1.aliyuncs.com/model-zoo/PETA/peta_32.pth

**Comment by v-vietlq** [comment]
Yes, I've modified it. Thank you very much

**Comment by ebenbaruch** [comment]
Thanks!!
